name: Build (macOS Intel)
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: macos-15-large
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup premake
        uses: Jarod42/install-premake5@v6

      - name: Run premake
        run: premake5 gmake2

      - name: Compile
        run: make -j config=release_x64 verbose=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./bin/
